apiVersion: {{ ascender_cr_api_version }}
kind: {{ ascender_backup_kind }}
metadata:
  name: ascender-backup-{{ ansible_date_time.date }}-{{ ansible_date_time.epoch }}
  namespace: {{ ASCENDER_NAMESPACE }}
spec:
  deployment_name: ascender-app
  clean_backup_on_delete: true